- name: Deploy Flask Docker App
  hosts: webserver
  become: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from Docker Hub
      shell: docker pull pranavanithya/flask-app:latest

    - name: Run Flask container
      shell: |
        docker rm -f flask-container || true
        docker run -d --name flask-container -p 5000:5000 pranavanithya/flask-app:latest
